export const ALLERGENS = [
  { id: "gluten",     label: "Gluten",          icon: "🌾", color: "#FFF3CD", text: "#856404" },
  { id: "crustaces",  label: "Crustacés",        icon: "🦐", color: "#FFE0E0", text: "#842029" },
  { id: "oeufs",      label: "Œufs",             icon: "🥚", color: "#FFF3CD", text: "#856404" },
  { id: "poissons",   label: "Poissons",          icon: "🐟", color: "#D0E8FF", text: "#084298" },
  { id: "arachides",  label: "Arachides",         icon: "🥜", color: "#FFE0E0", text: "#842029" },
  { id: "soja",       label: "Soja",              icon: "🫘", color: "#D4EDDA", text: "#155724" },
  { id: "lait",       label: "Lait",              icon: "🥛", color: "#D0E8FF", text: "#084298" },
  { id: "fruits_coq", label: "Fruits à coque",    icon: "🌰", color: "#FFF3CD", text: "#856404" },
  { id: "celeri",     label: "Céleri",            icon: "🥬", color: "#D4EDDA", text: "#155724" },
  { id: "moutarde",   label: "Moutarde",          icon: "🌿", color: "#FFF3CD", text: "#856404" },
  { id: "sesame",     label: "Sésame",            icon: "🌱", color: "#FFF3CD", text: "#856404" },
  { id: "so2",        label: "SO₂ / Sulfites",    icon: "🍷", color: "#F0D0E8", text: "#6A1040" },
  { id: "lupin",      label: "Lupin",             icon: "🌼", color: "#D4EDDA", text: "#155724" },
  { id: "mollusques", label: "Mollusques",        icon: "🦑", color: "#FFE0E0", text: "#842029" },
];

export const INGREDIENTS_DB = [

  // ── CÉRÉALES & GLUTEN ────────────────────────────────────────────────────
  { name: "farine de blé",              allergens: ["gluten"] },
  { name: "farine de blé complète",     allergens: ["gluten"] },
  { name: "farine",                     allergens: ["gluten"] },
  { name: "farine T45",                 allergens: ["gluten"] },
  { name: "farine T55",                 allergens: ["gluten"] },
  { name: "farine T65",                 allergens: ["gluten"] },
  { name: "farine T80",                 allergens: ["gluten"] },
  { name: "farine T110",                allergens: ["gluten"] },
  { name: "farine T150",                allergens: ["gluten"] },
  { name: "farine de seigle",           allergens: ["gluten"] },
  { name: "farine d'épeautre",          allergens: ["gluten"] },
  { name: "farine d'orge",              allergens: ["gluten"] },
  { name: "farine d'avoine",            allergens: ["gluten"] },
  { name: "farine de kamut",            allergens: ["gluten"] },
  { name: "farine de lupin",            allergens: ["gluten", "lupin"] },
  { name: "amidon de blé",              allergens: ["gluten"] },
  { name: "amidon",                     allergens: ["gluten"] },
  { name: "maïzena",                    allergens: [] },
  { name: "fécule de maïs",             allergens: [] },
  { name: "fécule de pomme de terre",   allergens: [] },
  { name: "fécule",                     allergens: [] },
  { name: "pain",                       allergens: ["gluten"] },
  { name: "pain de mie",                allergens: ["gluten", "lait"] },
  { name: "pain complet",               allergens: ["gluten"] },
  { name: "pain de campagne",           allergens: ["gluten"] },
  { name: "pain au levain",             allergens: ["gluten"] },
  { name: "pain brioche",               allergens: ["gluten", "lait", "oeufs"] },
  { name: "baguette",                   allergens: ["gluten"] },
  { name: "chapelure",                  allergens: ["gluten"] },
  { name: "chapelure panko",            allergens: ["gluten"] },
  { name: "biscottes",                  allergens: ["gluten", "lait"] },
  { name: "crackers",                   allergens: ["gluten"] },
  { name: "pain grillé",                allergens: ["gluten"] },
  { name: "croûtons",                   allergens: ["gluten", "lait"] },
  { name: "pâtes",                      allergens: ["gluten", "oeufs"] },
  { name: "pâtes fraîches",             allergens: ["gluten", "oeufs"] },
  { name: "pâtes sèches",               allergens: ["gluten"] },
  { name: "spaghetti",                  allergens: ["gluten"] },
  { name: "tagliatelles",               allergens: ["gluten", "oeufs"] },
  { name: "penne",                      allergens: ["gluten"] },
  { name: "fusilli",                    allergens: ["gluten"] },
  { name: "rigatoni",                   allergens: ["gluten"] },
  { name: "farfalle",                   allergens: ["gluten"] },
  { name: "lasagnes",                   allergens: ["gluten", "oeufs"] },
  { name: "gnocchi",                    allergens: ["gluten", "oeufs"] },
  { name: "ravioli",                    allergens: ["gluten", "oeufs"] },
  { name: "nouilles",                   allergens: ["gluten"] },
  { name: "nouilles de riz",            allergens: [] },
  { name: "vermicelles de riz",         allergens: [] },
  { name: "semoule",                    allergens: ["gluten"] },
  { name: "couscous",                   allergens: ["gluten"] },
  { name: "boulgour",                   allergens: ["gluten"] },
  { name: "orge",                       allergens: ["gluten"] },
  { name: "orge perlé",                 allergens: ["gluten"] },
  { name: "seigle",                     allergens: ["gluten"] },
  { name: "avoine",                     allergens: ["gluten"] },
  { name: "flocons d'avoine",           allergens: ["gluten"] },
  { name: "épeautre",                   allergens: ["gluten"] },
  { name: "kamut",                      allergens: ["gluten"] },
  { name: "blé",                        allergens: ["gluten"] },
  { name: "son de blé",                 allergens: ["gluten"] },
  { name: "germe de blé",               allergens: ["gluten"] },
  { name: "bière",                      allergens: ["gluten"] },
  { name: "bière blonde",               allergens: ["gluten"] },
  { name: "bière brune",                allergens: ["gluten"] },
  { name: "bière sans alcool",          allergens: ["gluten"] },
  { name: "levure de bière",            allergens: ["gluten"] },
  { name: "sauce soja",                 allergens: ["soja", "gluten"] },
  { name: "tamari",                     allergens: ["soja"] },
  { name: "miso",                       allergens: ["soja", "gluten"] },
  { name: "seitan",                     allergens: ["gluten"] },

  // ── RIZ & CÉRÉALES SANS GLUTEN ───────────────────────────────────────────
  { name: "riz",                        allergens: [] },
  { name: "riz basmati",                allergens: [] },
  { name: "riz thaï",                   allergens: [] },
  { name: "riz complet",                allergens: [] },
  { name: "riz arborio",                allergens: [] },
  { name: "riz soufflé",                allergens: [] },
  { name: "riz carnaroli",              allergens: [] },
  { name: "maïs",                       allergens: [] },
  { name: "polenta",                    allergens: [] },
  { name: "quinoa",                     allergens: [] },
  { name: "millet",                     allergens: [] },
  { name: "sarrasin",                   allergens: [] },
  { name: "farine de sarrasin",         allergens: [] },
  { name: "galette de sarrasin",        allergens: [] },
  { name: "teff",                       allergens: [] },
  { name: "amarante",                   allergens: [] },

  // ── PRODUITS LAITIERS ────────────────────────────────────────────────────
  { name: "lait",                       allergens: ["lait"] },
  { name: "lait entier",                allergens: ["lait"] },
  { name: "lait demi-écrémé",           allergens: ["lait"] },
  { name: "lait écrémé",                allergens: ["lait"] },
  { name: "lait en poudre",             allergens: ["lait"] },
  { name: "lait concentré",             allergens: ["lait"] },
  { name: "lait concentré sucré",       allergens: ["lait"] },
  { name: "lait de vache",              allergens: ["lait"] },
  { name: "lait de chèvre",             allergens: ["lait"] },
  { name: "lait de brebis",             allergens: ["lait"] },
  { name: "lait ribot",                 allergens: ["lait"] },
  { name: "lait fermenté",              allergens: ["lait"] },
  { name: "beurre",                     allergens: ["lait"] },
  { name: "beurre doux",                allergens: ["lait"] },
  { name: "beurre demi-sel",            allergens: ["lait"] },
  { name: "beurre salé",                allergens: ["lait"] },
  { name: "beurre clarifié",            allergens: ["lait"] },
  { name: "ghee",                       allergens: ["lait"] },
  { name: "margarine",                  allergens: ["lait"] },
  { name: "crème fraîche",              allergens: ["lait"] },
  { name: "crème fraîche épaisse",      allergens: ["lait"] },
  { name: "crème fraîche liquide",      allergens: ["lait"] },
  { name: "crème entière",              allergens: ["lait"] },
  { name: "crème légère",               allergens: ["lait"] },
  { name: "crème fleurette",            allergens: ["lait"] },
  { name: "crème chantilly",            allergens: ["lait"] },
  { name: "crème pâtissière",           allergens: ["lait", "oeufs", "gluten"] },
  { name: "crème anglaise",             allergens: ["lait", "oeufs"] },
  { name: "crème brûlée",               allergens: ["lait", "oeufs"] },
  { name: "crème au beurre",            allergens: ["lait", "oeufs"] },
  { name: "fromage",                    allergens: ["lait"] },
  { name: "fromage râpé",               allergens: ["lait"] },
  { name: "gruyère",                    allergens: ["lait"] },
  { name: "emmental",                   allergens: ["lait"] },
  { name: "comté",                      allergens: ["lait"] },
  { name: "beaufort",                   allergens: ["lait"] },
  { name: "abondance",                  allergens: ["lait"] },
  { name: "parmesan",                   allergens: ["lait"] },
  { name: "grana padano",               allergens: ["lait"] },
  { name: "pecorino",                   allergens: ["lait"] },
  { name: "mozzarella",                 allergens: ["lait"] },
  { name: "mozzarella di bufala",       allergens: ["lait"] },
  { name: "burrata",                    allergens: ["lait"] },
  { name: "ricotta",                    allergens: ["lait"] },
  { name: "mascarpone",                 allergens: ["lait"] },
  { name: "fromage blanc",              allergens: ["lait"] },
  { name: "fromage frais",              allergens: ["lait"] },
  { name: "petit suisse",               allergens: ["lait"] },
  { name: "faisselle",                  allergens: ["lait"] },
  { name: "cottage cheese",             allergens: ["lait"] },
  { name: "roquefort",                  allergens: ["lait"] },
  { name: "gorgonzola",                 allergens: ["lait"] },
  { name: "bleu d'auvergne",            allergens: ["lait"] },
  { name: "fourme d'ambert",            allergens: ["lait"] },
  { name: "brie",                       allergens: ["lait"] },
  { name: "camembert",                  allergens: ["lait"] },
  { name: "coulommiers",                allergens: ["lait"] },
  { name: "chaource",                   allergens: ["lait"] },
  { name: "munster",                    allergens: ["lait"] },
  { name: "époisses",                   allergens: ["lait"] },
  { name: "livarot",                    allergens: ["lait"] },
  { name: "maroilles",                  allergens: ["lait"] },
  { name: "pont-l'évêque",              allergens: ["lait"] },
  { name: "chèvre",                     allergens: ["lait"] },
  { name: "crottin de chavignol",       allergens: ["lait"] },
  { name: "saint-marcellin",            allergens: ["lait"] },
  { name: "saint-félicien",             allergens: ["lait"] },
  { name: "tomme",                      allergens: ["lait"] },
  { name: "raclette",                   allergens: ["lait"] },
  { name: "reblochon",                  allergens: ["lait"] },
  { name: "tartiflette",                allergens: ["lait"] },
  { name: "yaourt",                     allergens: ["lait"] },
  { name: "yaourt nature",              allergens: ["lait"] },
  { name: "yaourt grec",                allergens: ["lait"] },
  { name: "kéfir",                      allergens: ["lait"] },
  { name: "lassi",                      allergens: ["lait"] },
  { name: "lactosérum",                 allergens: ["lait"] },
  { name: "caséine",                    allergens: ["lait"] },
  { name: "lactose",                    allergens: ["lait"] },
  { name: "whey",                       allergens: ["lait"] },

  // ── ŒUFS ─────────────────────────────────────────────────────────────────
  { name: "œuf",                        allergens: ["oeufs"] },
  { name: "oeuf",                       allergens: ["oeufs"] },
  { name: "œufs",                       allergens: ["oeufs"] },
  { name: "oeufs",                      allergens: ["oeufs"] },
  { name: "œuf entier",                 allergens: ["oeufs"] },
  { name: "jaune d'œuf",                allergens: ["oeufs"] },
  { name: "jaune d'oeuf",               allergens: ["oeufs"] },
  { name: "blanc d'œuf",                allergens: ["oeufs"] },
  { name: "blanc d'oeuf",               allergens: ["oeufs"] },
  { name: "œuf de caille",              allergens: ["oeufs"] },
  { name: "œuf de poule",               allergens: ["oeufs"] },
  { name: "œuf mollet",                 allergens: ["oeufs"] },
  { name: "œuf poché",                  allergens: ["oeufs"] },
  { name: "œuf dur",                    allergens: ["oeufs"] },
  { name: "œuf au plat",                allergens: ["oeufs"] },
  { name: "omelette",                   allergens: ["oeufs"] },
  { name: "mayonnaise",                 allergens: ["oeufs", "moutarde"] },
  { name: "mayo",                       allergens: ["oeufs", "moutarde"] },
  { name: "aïoli",                      allergens: ["oeufs"] },
  { name: "hollandaise",                allergens: ["oeufs", "lait"] },
  { name: "béarnaise",                  allergens: ["oeufs", "lait"] },
  { name: "meringue",                   allergens: ["oeufs"] },
  { name: "appareil à quiche",          allergens: ["oeufs", "lait"] },
  { name: "migaine",                    allergens: ["oeufs", "lait"] },

  // ── VIANDES ──────────────────────────────────────────────────────────────
  { name: "bœuf",                       allergens: [] },
  { name: "boeuf",                      allergens: [] },
  { name: "steak",                      allergens: [] },
  { name: "steak haché",                allergens: [] },
  { name: "bavette",                    allergens: [] },
  { name: "entrecôte",                  allergens: [] },
  { name: "côte de bœuf",               allergens: [] },
  { name: "rumsteak",                   allergens: [] },
  { name: "faux-filet",                 allergens: [] },
  { name: "filet de bœuf",              allergens: [] },
  { name: "tournedos",                  allergens: [] },
  { name: "rosbif",                     allergens: [] },
  { name: "bœuf bourguignon",           allergens: [] },
  { name: "pot-au-feu",                 allergens: [] },
  { name: "joue de bœuf",               allergens: [] },
  { name: "paleron",                    allergens: [] },
  { name: "gîte",                       allergens: [] },
  { name: "macreuse",                   allergens: [] },
  { name: "jarret de bœuf",             allergens: [] },
  { name: "queue de bœuf",              allergens: [] },
  { name: "hampe",                      allergens: [] },
  { name: "onglet",                     allergens: [] },
  { name: "araignée",                   allergens: [] },
  { name: "veau",                       allergens: [] },
  { name: "côte de veau",               allergens: [] },
  { name: "escalope de veau",           allergens: [] },
  { name: "blanquette de veau",         allergens: [] },
  { name: "jarret de veau",             allergens: [] },
  { name: "foie de veau",               allergens: [] },
  { name: "ris de veau",                allergens: [] },
  { name: "porc",                       allergens: [] },
  { name: "côte de porc",               allergens: [] },
  { name: "filet de porc",              allergens: [] },
  { name: "rôti de porc",               allergens: [] },
  { name: "échine de porc",             allergens: [] },
  { name: "poitrine de porc",           allergens: [] },
  { name: "lardons",                    allergens: [] },
  { name: "lardon",                     allergens: [] },
  { name: "lardons fumés",              allergens: [] },
  { name: "lardons nature",             allergens: [] },
  { name: "bacon",                      allergens: [] },
  { name: "jambon",                     allergens: [] },
  { name: "jambon blanc",               allergens: [] },
  { name: "jambon cuit",                allergens: [] },
  { name: "jambon cru",                 allergens: [] },
  { name: "jambon de Parme",            allergens: [] },
  { name: "jambon de Bayonne",          allergens: [] },
  { name: "prosciutto",                 allergens: [] },
  { name: "jambon serrano",             allergens: [] },
  { name: "pancetta",                   allergens: [] },
  { name: "guanciale",                  allergens: [] },
  { name: "coppa",                      allergens: [] },
  { name: "bresaola",                   allergens: [] },
  { name: "saucisse",                   allergens: [] },
  { name: "saucisson",                  allergens: [] },
  { name: "chorizo",                    allergens: [] },
  { name: "merguez",                    allergens: [] },
  { name: "chipolata",                  allergens: [] },
  { name: "knack",                      allergens: [] },
  { name: "frankfurter",                allergens: [] },
  { name: "boudin noir",                allergens: [] },
  { name: "boudin blanc",               allergens: ["lait", "gluten"] },
  { name: "andouillette",               allergens: [] },
  { name: "andouille",                  allergens: [] },
  { name: "mortadelle",                 allergens: [] },
  { name: "rillettes",                  allergens: [] },
  { name: "pâté",                       allergens: [] },
  { name: "foie gras",                  allergens: [] },
  { name: "terrine",                    allergens: [] },
  { name: "mouton",                     allergens: [] },
  { name: "agneau",                     allergens: [] },
  { name: "côtelette d'agneau",         allergens: [] },
  { name: "gigot d'agneau",             allergens: [] },
  { name: "épaule d'agneau",            allergens: [] },
  { name: "carré d'agneau",             allergens: [] },
  { name: "navarin d'agneau",           allergens: [] },
  { name: "cheval",                     allergens: [] },
  { name: "gibier",                     allergens: [] },
  { name: "cerf",                       allergens: [] },
  { name: "chevreuil",                  allergens: [] },
  { name: "sanglier",                   allergens: [] },
  { name: "lapin",                      allergens: [] },
  { name: "lièvre",                     allergens: [] },
  { name: "canard",                     allergens: [] },
  { name: "magret de canard",           allergens: [] },
  { name: "confit de canard",           allergens: [] },
  { name: "cuisse de canard",           allergens: [] },
  { name: "aiguillette de canard",      allergens: [] },
  { name: "foie de canard",             allergens: [] },
  { name: "poulet",                     allergens: [] },
  { name: "blanc de poulet",            allergens: [] },
  { name: "cuisse de poulet",           allergens: [] },
  { name: "pilon de poulet",            allergens: [] },
  { name: "aile de poulet",             allergens: [] },
  { name: "poulet rôti",                allergens: [] },
  { name: "dinde",                      allergens: [] },
  { name: "escalope de dinde",          allergens: [] },
  { name: "pintade",                    allergens: [] },
  { name: "caille",                     allergens: [] },
  { name: "pigeon",                     allergens: [] },
  { name: "faisan",                     allergens: [] },

  // ── POISSONS ─────────────────────────────────────────────────────────────
  { name: "saumon",                     allergens: ["poissons"] },
  { name: "saumon frais",               allergens: ["poissons"] },
  { name: "saumon fumé",                allergens: ["poissons"] },
  { name: "saumon gravlax",             allergens: ["poissons"] },
  { name: "saumon d'Écosse",            allergens: ["poissons"] },
  { name: "thon",                       allergens: ["poissons"] },
  { name: "thon rouge",                 allergens: ["poissons"] },
  { name: "thon en boîte",              allergens: ["poissons"] },
  { name: "cabillaud",                  allergens: ["poissons"] },
  { name: "morue",                      allergens: ["poissons"] },
  { name: "brandade",                   allergens: ["poissons", "lait"] },
  { name: "sardine",                    allergens: ["poissons"] },
  { name: "sardines en boîte",          allergens: ["poissons"] },
  { name: "anchois",                    allergens: ["poissons", "so2"] },
  { name: "filets d'anchois",           allergens: ["poissons"] },
  { name: "pâte d'anchois",             allergens: ["poissons"] },
  { name: "dorade",                     allergens: ["poissons"] },
  { name: "daurade",                    allergens: ["poissons"] },
  { name: "bar",                        allergens: ["poissons"] },
  { name: "loup de mer",                allergens: ["poissons"] },
  { name: "sole",                       allergens: ["poissons"] },
  { name: "turbot",                     allergens: ["poissons"] },
  { name: "Saint-Pierre",               allergens: ["poissons"] },
  { name: "flétan",                     allergens: ["poissons"] },
  { name: "limande",                    allergens: ["poissons"] },
  { name: "raie",                       allergens: ["poissons"] },
  { name: "rouget",                     allergens: ["poissons"] },
  { name: "rouget barbet",              allergens: ["poissons"] },
  { name: "grondin",                    allergens: ["poissons"] },
  { name: "merlu",                      allergens: ["poissons"] },
  { name: "colin",                      allergens: ["poissons"] },
  { name: "lieu noir",                  allergens: ["poissons"] },
  { name: "lieu jaune",                 allergens: ["poissons"] },
  { name: "maquereau",                  allergens: ["poissons"] },
  { name: "hareng",                     allergens: ["poissons", "so2"] },
  { name: "hareng fumé",                allergens: ["poissons", "so2"] },
  { name: "rollmops",                   allergens: ["poissons"] },
  { name: "truite",                     allergens: ["poissons"] },
  { name: "truite fumée",               allergens: ["poissons"] },
  { name: "truite arc-en-ciel",         allergens: ["poissons"] },
  { name: "brème",                      allergens: ["poissons"] },
  { name: "carpe",                      allergens: ["poissons"] },
  { name: "perche",                     allergens: ["poissons"] },
  { name: "brochet",                    allergens: ["poissons"] },
  { name: "anguille",                   allergens: ["poissons"] },
  { name: "espadon",                    allergens: ["poissons"] },
  { name: "requin",                     allergens: ["poissons"] },
  { name: "lotte",                      allergens: ["poissons"] },
  { name: "baudroie",                   allergens: ["poissons"] },
  { name: "poisson pané",               allergens: ["poissons", "gluten"] },
  { name: "sauce worcestershire",       allergens: ["poissons", "gluten"] },
  { name: "nuoc-mâm",                   allergens: ["poissons"] },
  { name: "sauce nuoc-mâm",             allergens: ["poissons"] },
  { name: "sauce poisson",              allergens: ["poissons"] },
  { name: "garum",                      allergens: ["poissons"] },

  // ── CRUSTACÉS ────────────────────────────────────────────────────────────
  { name: "crevette",                   allergens: ["crustaces"] },
  { name: "crevettes",                  allergens: ["crustaces"] },
  { name: "crevettes roses",            allergens: ["crustaces"] },
  { name: "crevettes grises",           allergens: ["crustaces"] },
  { name: "gambas",                     allergens: ["crustaces"] },
  { name: "bouquet",                    allergens: ["crustaces"] },
  { name: "homard",                     allergens: ["crustaces"] },
  { name: "langouste",                  allergens: ["crustaces"] },
  { name: "langoustine",                allergens: ["crustaces"] },
  { name: "crabe",                      allergens: ["crustaces"] },
  { name: "tourteau",                   allergens: ["crustaces"] },
  { name: "araignée de mer",            allergens: ["crustaces"] },
  { name: "étrille",                    allergens: ["crustaces"] },
  { name: "écrevisse",                  allergens: ["crustaces"] },
  { name: "bernique",                   allergens: ["crustaces"] },

  // ── MOLLUSQUES ───────────────────────────────────────────────────────────
  { name: "moule",                      allergens: ["mollusques"] },
  { name: "moules",                     allergens: ["mollusques"] },
  { name: "moules marinières",          allergens: ["mollusques"] },
  { name: "huître",                     allergens: ["mollusques"] },
  { name: "huîtres",                    allergens: ["mollusques"] },
  { name: "coquille Saint-Jacques",     allergens: ["mollusques"] },
  { name: "noix de Saint-Jacques",      allergens: ["mollusques"] },
  { name: "palourde",                   allergens: ["mollusques"] },
  { name: "palourdes",                  allergens: ["mollusques"] },
  { name: "clam",                       allergens: ["mollusques"] },
  { name: "couteau",                    allergens: ["mollusques"] },
  { name: "praire",                     allergens: ["mollusques"] },
  { name: "bigorneaux",                 allergens: ["mollusques"] },
  { name: "bulot",                      allergens: ["mollusques"] },
  { name: "bulots",                     allergens: ["mollusques"] },
  { name: "calamar",                    allergens: ["mollusques"] },
  { name: "calmar",                     allergens: ["mollusques"] },
  { name: "encornet",                   allergens: ["mollusques"] },
  { name: "seiche",                     allergens: ["mollusques"] },
  { name: "pieuvre",                    allergens: ["mollusques"] },
  { name: "poulpe",                     allergens: ["mollusques"] },
  { name: "chipirons",                  allergens: ["mollusques"] },

  // ── SOJA ─────────────────────────────────────────────────────────────────
  { name: "soja",                       allergens: ["soja"] },
  { name: "tofu",                       allergens: ["soja"] },
  { name: "tofu ferme",                 allergens: ["soja"] },
  { name: "tofu soyeux",                allergens: ["soja"] },
  { name: "tofu fumé",                  allergens: ["soja"] },
  { name: "edamame",                    allergens: ["soja"] },
  { name: "haricots de soja",           allergens: ["soja"] },
  { name: "lait de soja",               allergens: ["soja"] },
  { name: "crème de soja",              allergens: ["soja"] },
  { name: "yaourt de soja",             allergens: ["soja"] },
  { name: "tempeh",                     allergens: ["soja"] },
  { name: "natto",                      allergens: ["soja"] },
  { name: "protéines de soja",          allergens: ["soja"] },
  { name: "huile de soja",              allergens: ["soja"] },
  { name: "lécithine de soja",          allergens: ["soja"] },

  // ── ARACHIDES ────────────────────────────────────────────────────────────
  { name: "cacahuète",                  allergens: ["arachides"] },
  { name: "cacahuètes",                 allergens: ["arachides"] },
  { name: "arachide",                   allergens: ["arachides"] },
  { name: "beurre de cacahuète",        allergens: ["arachides"] },
  { name: "huile d'arachide",           allergens: ["arachides"] },
  { name: "pâte d'arachide",            allergens: ["arachides"] },
  { name: "satay",                      allergens: ["arachides"] },
  { name: "sauce satay",                allergens: ["arachides"] },

  // ── FRUITS À COQUE ───────────────────────────────────────────────────────
  { name: "amande",                     allergens: ["fruits_coq"] },
  { name: "amandes",                    allergens: ["fruits_coq"] },
  { name: "amandes effilées",           allergens: ["fruits_coq"] },
  { name: "amandes concassées",         allergens: ["fruits_coq"] },
  { name: "amandes grillées",           allergens: ["fruits_coq"] },
  { name: "poudre d'amande",            allergens: ["fruits_coq"] },
  { name: "pâte d'amande",              allergens: ["fruits_coq"] },
  { name: "massepain",                  allergens: ["fruits_coq"] },
  { name: "orgeat",                     allergens: ["fruits_coq"] },
  { name: "lait d'amande",              allergens: ["fruits_coq"] },
  { name: "crème d'amande",             allergens: ["fruits_coq"] },
  { name: "frangipane",                 allergens: ["fruits_coq", "oeufs", "lait", "gluten"] },
  { name: "noix",                       allergens: ["fruits_coq"] },
  { name: "cerneaux de noix",           allergens: ["fruits_coq"] },
  { name: "noix de Grenoble",           allergens: ["fruits_coq"] },
  { name: "noisette",                   allergens: ["fruits_coq"] },
  { name: "noisettes",                  allergens: ["fruits_coq"] },
  { name: "noisettes grillées",         allergens: ["fruits_coq"] },
  { name: "pralin",                     allergens: ["fruits_coq"] },
  { name: "pralinoise",                 allergens: ["fruits_coq"] },
  { name: "praliné",                    allergens: ["fruits_coq"] },
  { name: "gianduja",                   allergens: ["fruits_coq", "lait"] },
  { name: "pâte noisette",              allergens: ["fruits_coq"] },
  { name: "lait de noisette",           allergens: ["fruits_coq"] },
  { name: "pistache",                   allergens: ["fruits_coq"] },
  { name: "pistaches",                  allergens: ["fruits_coq"] },
  { name: "pâte de pistache",           allergens: ["fruits_coq"] },
  { name: "noix de cajou",              allergens: ["fruits_coq"] },
  { name: "noix de macadamia",          allergens: ["fruits_coq"] },
  { name: "noix du Brésil",             allergens: ["fruits_coq"] },
  { name: "noix de pécan",              allergens: ["fruits_coq"] },
  { name: "noix de coco",               allergens: ["fruits_coq"] },
  { name: "lait de coco",               allergens: ["fruits_coq"] },
  { name: "crème de coco",              allergens: ["fruits_coq"] },
  { name: "noix de coco râpée",         allergens: ["fruits_coq"] },
  { name: "huile de coco",              allergens: ["fruits_coq"] },
  { name: "châtaigne",                  allergens: ["fruits_coq"] },
  { name: "châtaignes",                 allergens: ["fruits_coq"] },
  { name: "marron",                     allergens: ["fruits_coq"] },
  { name: "crème de marron",            allergens: ["fruits_coq"] },
  { name: "pignon de pin",              allergens: ["fruits_coq"] },
  { name: "pignons",                    allergens: ["fruits_coq"] },
  { name: "noix de kola",               allergens: ["fruits_coq"] },

  // ── MOUTARDE ─────────────────────────────────────────────────────────────
  { name: "moutarde",                   allergens: ["moutarde"] },
  { name: "moutarde de Dijon",          allergens: ["moutarde"] },
  { name: "moutarde à l'ancienne",      allergens: ["moutarde"] },
  { name: "moutarde forte",             allergens: ["moutarde"] },
  { name: "moutarde douce",             allergens: ["moutarde"] },
  { name: "moutarde en grains",         allergens: ["moutarde"] },
  { name: "graine de moutarde",         allergens: ["moutarde"] },
  { name: "graines de moutarde",        allergens: ["moutarde"] },
  { name: "sauce moutarde",             allergens: ["moutarde"] },
  { name: "vinaigrette moutarde",       allergens: ["moutarde"] },
  { name: "poudre de moutarde",         allergens: ["moutarde"] },

  // ── SÉSAME ───────────────────────────────────────────────────────────────
  { name: "sésame",                     allergens: ["sesame"] },
  { name: "graines de sésame",          allergens: ["sesame"] },
  { name: "sésame noir",                allergens: ["sesame"] },
  { name: "tahini",                     allergens: ["sesame"] },
  { name: "tahin",                      allergens: ["sesame"] },
  { name: "huile de sésame",            allergens: ["sesame"] },
  { name: "pâte de sésame",             allergens: ["sesame"] },
  { name: "houmous",                    allergens: ["sesame"] },
  { name: "hummus",                     allergens: ["sesame"] },

  // ── CÉLERI ───────────────────────────────────────────────────────────────
  { name: "céleri",                     allergens: ["celeri"] },
  { name: "céleri-rave",                allergens: ["celeri"] },
  { name: "céleri branche",             allergens: ["celeri"] },
  { name: "branche de céleri",          allergens: ["celeri"] },
  { name: "sel de céleri",              allergens: ["celeri"] },
  { name: "graines de céleri",          allergens: ["celeri"] },

  // ── SO2 / SULFITES ───────────────────────────────────────────────────────
  { name: "vin",                        allergens: ["so2"] },
  { name: "vin blanc",                  allergens: ["so2"] },
  { name: "vin rouge",                  allergens: ["so2"] },
  { name: "vin rosé",                   allergens: ["so2"] },
  { name: "champagne",                  allergens: ["so2"] },
  { name: "crémant",                    allergens: ["so2"] },
  { name: "prosecco",                   allergens: ["so2"] },
  { name: "cava",                       allergens: ["so2"] },
  { name: "porto",                      allergens: ["so2"] },
  { name: "cognac",                     allergens: ["so2"] },
  { name: "armagnac",                   allergens: ["so2"] },
  { name: "sherry",                     allergens: ["so2"] },
  { name: "xérès",                      allergens: ["so2"] },
  { name: "vinaigre",                   allergens: ["so2"] },
  { name: "vinaigre de vin",            allergens: ["so2"] },
  { name: "vinaigre balsamique",        allergens: ["so2"] },
  { name: "vinaigre blanc",             allergens: [] },
  { name: "vinaigre de cidre",          allergens: [] },
  { name: "raisins secs",               allergens: ["so2"] },
  { name: "abricots secs",              allergens: ["so2"] },
  { name: "pruneaux",                   allergens: ["so2"] },
  { name: "fruits secs",                allergens: ["so2"] },
  { name: "figues sèches",              allergens: ["so2"] },
  { name: "dattes",                     allergens: [] },
  { name: "gelée de vin",               allergens: ["so2"] },
  { name: "jus de raisin",              allergens: ["so2"] },

  // ── LUPIN ────────────────────────────────────────────────────────────────
  { name: "lupin",                      allergens: ["lupin"] },
  { name: "graine de lupin",            allergens: ["lupin"] },
  { name: "graines de lupin",           allergens: ["lupin"] },
  { name: "farine de lupin",            allergens: ["lupin", "gluten"] },
  { name: "protéines de lupin",         allergens: ["lupin"] },

  // ── LÉGUMES ──────────────────────────────────────────────────────────────
  { name: "tomate",                     allergens: [] },
  { name: "tomates",                    allergens: [] },
  { name: "tomate cerise",              allergens: [] },
  { name: "tomate olivette",            allergens: [] },
  { name: "tomate grappe",              allergens: [] },
  { name: "tomate concassée",           allergens: [] },
  { name: "purée de tomate",            allergens: [] },
  { name: "coulis de tomate",           allergens: [] },
  { name: "concentré de tomate",        allergens: [] },
  { name: "tomates pelées",             allergens: [] },
  { name: "tomates séchées",            allergens: [] },
  { name: "tomates confites",           allergens: [] },
  { name: "ketchup",                    allergens: [] },
  { name: "oignon",                     allergens: [] },
  { name: "oignons",                    allergens: [] },
  { name: "oignon rouge",               allergens: [] },
  { name: "oignon jaune",               allergens: [] },
  { name: "oignon blanc",               allergens: [] },
  { name: "oignon nouveau",             allergens: [] },
  { name: "échalote",                   allergens: [] },
  { name: "échalotes",                  allergens: [] },
  { name: "ail",                        allergens: [] },
  { name: "gousse d'ail",               allergens: [] },
  { name: "ail haché",                  allergens: [] },
  { name: "ail en poudre",              allergens: [] },
  { name: "poireau",                    allergens: [] },
  { name: "poireaux",                   allergens: [] },
  { name: "blanc de poireau",           allergens: [] },
  { name: "carotte",                    allergens: [] },
  { name: "carottes",                   allergens: [] },
  { name: "carotte râpée",              allergens: [] },
  { name: "pomme de terre",             allergens: [] },
  { name: "pommes de terre",            allergens: [] },
  { name: "pomme de terre ratte",       allergens: [] },
  { name: "pomme de terre charlotte",   allergens: [] },
  { name: "pomme de terre bintje",      allergens: [] },
  { name: "purée de pomme de terre",    allergens: ["lait"] },
  { name: "gratin dauphinois",          allergens: ["lait"] },
  { name: "courgette",                  allergens: [] },
  { name: "courgettes",                 allergens: [] },
  { name: "aubergine",                  allergens: [] },
  { name: "aubergines",                 allergens: [] },
  { name: "poivron",                    allergens: [] },
  { name: "poivrons",                   allergens: [] },
  { name: "poivron rouge",              allergens: [] },
  { name: "poivron vert",               allergens: [] },
  { name: "poivron jaune",              allergens: [] },
  { name: "piment",                     allergens: [] },
  { name: "piment rouge",               allergens: [] },
  { name: "piment vert",                allergens: [] },
  { name: "piment d'Espelette",         allergens: [] },
  { name: "champignon",                 allergens: [] },
  { name: "champignons",                allergens: [] },
  { name: "champignon de Paris",        allergens: [] },
  { name: "champignons de Paris",       allergens: [] },
  { name: "cèpe",                       allergens: [] },
  { name: "cèpes",                      allergens: [] },
  { name: "morille",                    allergens: [] },
  { name: "morilles",                   allergens: [] },
  { name: "truffe",                     allergens: [] },
  { name: "truffes",                    allergens: [] },
  { name: "girolles",                   allergens: [] },
  { name: "chanterelle",                allergens: [] },
  { name: "shiitake",                   allergens: [] },
  { name: "pleurote",                   allergens: [] },
  { name: "épinard",                    allergens: [] },
  { name: "épinards",                   allergens: [] },
  { name: "salade",                     allergens: [] },
  { name: "salade verte",               allergens: [] },
  { name: "laitue",                     allergens: [] },
  { name: "roquette",                   allergens: [] },
  { name: "mâche",                      allergens: [] },
  { name: "frisée",                     allergens: [] },
  { name: "endive",                     allergens: [] },
  { name: "chicorée",                   allergens: [] },
  { name: "mesclun",                    allergens: [] },
  { name: "cresson",                    allergens: [] },
  { name: "pourpier",                   allergens: [] },
  { name: "brocoli",                    allergens: [] },
  { name: "chou-fleur",                 allergens: [] },
  { name: "chou",                       allergens: [] },
  { name: "chou blanc",                 allergens: [] },
  { name: "chou rouge",                 allergens: [] },
  { name: "chou vert",                  allergens: [] },
  { name: "chou de Bruxelles",          allergens: [] },
  { name: "chou romanesco",             allergens: [] },
  { name: "chou-rave",                  allergens: [] },
  { name: "chou frisé",                 allergens: [] },
  { name: "kale",                       allergens: [] },
  { name: "artichaut",                  allergens: [] },
  { name: "asperge",                    allergens: [] },
  { name: "asperges",                   allergens: [] },
  { name: "asperges vertes",            allergens: [] },
  { name: "asperges blanches",          allergens: [] },
  { name: "haricot vert",               allergens: [] },
  { name: "haricots verts",             allergens: [] },
  { name: "haricot blanc",              allergens: [] },
  { name: "haricots blancs",            allergens: [] },
  { name: "haricot rouge",              allergens: [] },
  { name: "haricots rouges",            allergens: [] },
  { name: "flageolet",                  allergens: [] },
  { name: "petits pois",                allergens: [] },
  { name: "pois chiche",                allergens: [] },
  { name: "pois chiches",               allergens: [] },
  { name: "lentille",                   allergens: [] },
  { name: "lentilles",                  allergens: [] },
  { name: "lentilles vertes",           allergens: [] },
  { name: "lentilles corail",           allergens: [] },
  { name: "lentilles beluga",           allergens: [] },
  { name: "fève",                       allergens: [] },
  { name: "fèves",                      allergens: [] },
  { name: "pois cassé",                 allergens: [] },
  { name: "pois cassés",                allergens: [] },
  { name: "navet",                      allergens: [] },
  { name: "radis",                      allergens: [] },
  { name: "radis noir",                 allergens: [] },
  { name: "betterave",                  allergens: [] },
  { name: "betterave rouge",            allergens: [] },
  { name: "topinambour",                allergens: [] },
  { name: "panais",                     allergens: [] },
  { name: "salsifis",                   allergens: [] },
  { name: "fenouil",                    allergens: [] },
  { name: "concombre",                  allergens: [] },
  { name: "cornichon",                  allergens: [] },
  { name: "cornichons",                 allergens: [] },
  { name: "courgette jaune",            allergens: [] },
  { name: "butternut",                  allergens: [] },
  { name: "potiron",                    allergens: [] },
  { name: "potimarron",                 allergens: [] },
  { name: "courge",                     allergens: [] },
  { name: "citrouille",                 allergens: [] },
  { name: "avocat",                     allergens: [] },
  { name: "guacamole",                  allergens: [] },
  { name: "bette",                      allergens: [] },
  { name: "blette",                     allergens: [] },

  // ── FRUITS ───────────────────────────────────────────────────────────────
  { name: "pomme",                      allergens: [] },
  { name: "pommes",                     allergens: [] },
  { name: "poire",                      allergens: [] },
  { name: "poires",                     allergens: [] },
  { name: "abricot",                    allergens: [] },
  { name: "abricots",                   allergens: [] },
  { name: "pêche",                      allergens: [] },
  { name: "pêches",                     allergens: [] },
  { name: "nectarine",                  allergens: [] },
  { name: "brugnon",                    allergens: [] },
  { name: "prune",                      allergens: [] },
  { name: "prunes",                     allergens: [] },
  { name: "quetsche",                   allergens: [] },
  { name: "mirabelle",                  allergens: [] },
  { name: "cerise",                     allergens: [] },
  { name: "cerises",                    allergens: [] },
  { name: "griotte",                    allergens: [] },
  { name: "fraise",                     allergens: [] },
  { name: "fraises",                    allergens: [] },
  { name: "framboise",                  allergens: [] },
  { name: "framboises",                 allergens: [] },
  { name: "myrtille",                   allergens: [] },
  { name: "myrtilles",                  allergens: [] },
  { name: "cassis",                     allergens: [] },
  { name: "groseille",                  allergens: [] },
  { name: "groseilles",                 allergens: [] },
  { name: "mûre",                       allergens: [] },
  { name: "mûres",                      allergens: [] },
  { name: "kiwi",                       allergens: [] },
  { name: "mangue",                     allergens: [] },
  { name: "ananas",                     allergens: [] },
  { name: "papaye",                     allergens: [] },
  { name: "litchi",                     allergens: [] },
  { name: "fruit de la passion",        allergens: [] },
  { name: "maracuja",                   allergens: [] },
  { name: "grenade",                    allergens: [] },
  { name: "figue",                      allergens: [] },
  { name: "figues",                     allergens: [] },
  { name: "melon",                      allergens: [] },
  { name: "pastèque",                   allergens: [] },
  { name: "raisin",                     allergens: [] },
  { name: "raisins",                    allergens: [] },
  { name: "raisin blanc",               allergens: [] },
  { name: "raisin noir",                allergens: [] },
  { name: "orange",                     allergens: [] },
  { name: "oranges",                    allergens: [] },
  { name: "clémentine",                 allergens: [] },
  { name: "mandarine",                  allergens: [] },
  { name: "citron",                     allergens: [] },
  { name: "citrons",                    allergens: [] },
  { name: "citron vert",                allergens: [] },
  { name: "lime",                       allergens: [] },
  { name: "pamplemousse",               allergens: [] },
  { name: "bergamote",                  allergens: [] },
  { name: "yuzu",                       allergens: [] },
  { name: "banane",                     allergens: [] },
  { name: "bananes",                    allergens: [] },

  // ── HERBES AROMATIQUES ───────────────────────────────────────────────────
  { name: "persil",                     allergens: [] },
  { name: "persil plat",                allergens: [] },
  { name: "persil frisé",               allergens: [] },
  { name: "basilic",                    allergens: [] },
  { name: "coriandre",                  allergens: [] },
  { name: "ciboulette",                 allergens: [] },
  { name: "estragon",                   allergens: [] },
  { name: "thym",                       allergens: [] },
  { name: "romarin",                    allergens: [] },
  { name: "laurier",                    allergens: [] },
  { name: "sauge",                      allergens: [] },
  { name: "menthe",                     allergens: [] },
  { name: "menthe fraîche",             allergens: [] },
  { name: "origan",                     allergens: [] },
  { name: "marjolaine",                 allergens: [] },
  { name: "sarriette",                  allergens: [] },
  { name: "aneth",                      allergens: [] },
  { name: "fenouil",                    allergens: [] },
  { name: "cerfeuil",                   allergens: [] },
  { name: "oseille",                    allergens: [] },
  { name: "citronnelle",                allergens: [] },
  { name: "verveine",                   allergens: [] },
  { name: "bouquet garni",              allergens: [] },
  { name: "fines herbes",               allergens: [] },
  { name: "herbes de Provence",         allergens: [] },

  // ── ÉPICES ───────────────────────────────────────────────────────────────
  { name: "poivre",                     allergens: [] },
  { name: "poivre noir",                allergens: [] },
  { name: "poivre blanc",               allergens: [] },
  { name: "poivre rose",                allergens: [] },
  { name: "poivre de Sichuan",          allergens: [] },
  { name: "poivre long",                allergens: [] },
  { name: "sel",                        allergens: [] },
  { name: "fleur de sel",               allergens: [] },
  { name: "sel fin",                    allergens: [] },
  { name: "gros sel",                   allergens: [] },
  { name: "sel de Guérande",            allergens: [] },
  { name: "paprika",                    allergens: [] },
  { name: "paprika fumé",               allergens: [] },
  { name: "cumin",                      allergens: [] },
  { name: "curry",                      allergens: [] },
  { name: "curcuma",                    allergens: [] },
  { name: "cannelle",                   allergens: [] },
  { name: "cardamome",                  allergens: [] },
  { name: "clou de girofle",            allergens: [] },
  { name: "noix de muscade",            allergens: [] },
  { name: "muscade",                    allergens: [] },
  { name: "anis étoilé",                allergens: [] },
  { name: "badiane",                    allergens: [] },
  { name: "anis",                       allergens: [] },
  { name: "gingembre",                  allergens: [] },
  { name: "gingembre frais",            allergens: [] },
  { name: "gingembre en poudre",        allergens: [] },
  { name: "safran",                     allergens: [] },
  { name: "vanille",                    allergens: [] },
  { name: "gousse de vanille",          allergens: [] },
  { name: "extrait de vanille",         allergens: [] },
  { name: "vanilline",                  allergens: [] },
  { name: "fenugrec",                   allergens: [] },
  { name: "coriandre en poudre",        allergens: [] },
  { name: "ras el hanout",              allergens: [] },
  { name: "zaatar",                     allergens: ["sesame"] },
  { name: "za'atar",                    allergens: ["sesame"] },
  { name: "sumac",                      allergens: [] },
  { name: "piment de la Jamaïque",      allergens: [] },
  { name: "quatre-épices",              allergens: [] },
  { name: "mélange de cinq épices",     allergens: [] },
  { name: "colombo",                    allergens: [] },
  { name: "massalé",                    allergens: [] },
  { name: "harissa",                    allergens: [] },
  { name: "sauce piri-piri",            allergens: [] },
  { name: "tabasco",                    allergens: [] },

  // ── HUILES & MATIÈRES GRASSES ────────────────────────────────────────────
  { name: "huile d'olive",              allergens: [] },
  { name: "huile d'olive extra vierge", allergens: [] },
  { name: "huile de tournesol",         allergens: [] },
  { name: "huile de colza",             allergens: [] },
  { name: "huile de pépins de raisin",  allergens: [] },
  { name: "huile de noix",              allergens: ["fruits_coq"] },
  { name: "huile de noisette",          allergens: ["fruits_coq"] },
  { name: "huile de pistache",          allergens: ["fruits_coq"] },
  { name: "huile de palme",             allergens: [] },
  { name: "huile végétale",             allergens: [] },
  { name: "saindoux",                   allergens: [] },
  { name: "graisse de canard",          allergens: [] },
  { name: "graisse d'oie",              allergens: [] },

  // ── SUCRES & SUCRERIES ───────────────────────────────────────────────────
  { name: "sucre",                      allergens: [] },
  { name: "sucre blanc",                allergens: [] },
  { name: "sucre roux",                 allergens: [] },
  { name: "sucre de canne",             allergens: [] },
  { name: "sucre glace",                allergens: [] },
  { name: "sucre en poudre",            allergens: [] },
  { name: "sucre cristal",              allergens: [] },
  { name: "sucre muscovado",            allergens: [] },
  { name: "cassonade",                  allergens: [] },
  { name: "vergeoise",                  allergens: [] },
  { name: "miel",                       allergens: [] },
  { name: "sirop d'érable",             allergens: [] },
  { name: "sirop de glucose",           allergens: [] },
  { name: "sirop d'agave",              allergens: [] },
  { name: "mélasse",                    allergens: [] },
  { name: "caramel",                    allergens: [] },
  { name: "caramel au beurre salé",     allergens: ["lait"] },
  { name: "chocolat",                   allergens: ["lait"] },
  { name: "chocolat noir",              allergens: [] },
  { name: "chocolat au lait",           allergens: ["lait"] },
  { name: "chocolat blanc",             allergens: ["lait"] },
  { name: "chocolat de couverture",     allergens: [] },
  { name: "cacao",                      allergens: [] },
  { name: "cacao en poudre",            allergens: [] },
  { name: "pâte de cacao",              allergens: [] },
  { name: "beurre de cacao",            allergens: [] },
  { name: "pépites de chocolat",        allergens: ["lait"] },
  { name: "nutella",                    allergens: ["fruits_coq", "lait", "gluten"] },
  { name: "confiture",                  allergens: [] },
  { name: "gelée",                      allergens: [] },
  { name: "marmelade",                  allergens: [] },

  // ── LEVURES & AGENTS LEVANTS ─────────────────────────────────────────────
  { name: "levure",                     allergens: [] },
  { name: "levure boulangère",          allergens: [] },
  { name: "levure chimique",            allergens: [] },
  { name: "levure instantanée",         allergens: [] },
  { name: "bicarbonate de soude",       allergens: [] },
  { name: "bicarbonate",                allergens: [] },

  // ── SAUCES & CONDIMENTS ──────────────────────────────────────────────────
  { name: "sauce soja",                 allergens: ["soja", "gluten"] },
  { name: "sauce soja salée",           allergens: ["soja", "gluten"] },
  { name: "sauce soja sucrée",          allergens: ["soja", "gluten"] },
  { name: "tamari",                     allergens: ["soja"] },
  { name: "sauce hoisin",               allergens: ["soja", "gluten"] },
  { name: "sauce oyster",               allergens: ["mollusques"] },
  { name: "sauce aux huîtres",          allergens: ["mollusques"] },
  { name: "sauce teriyaki",             allergens: ["soja", "gluten"] },
  { name: "sauce ponzu",                allergens: ["poissons", "soja"] },
  { name: "sauce barbecue",             allergens: [] },
  { name: "ketchup",                    allergens: [] },
  { name: "sauce tomate",               allergens: [] },
  { name: "coulis de tomate",           allergens: [] },
  { name: "sauce béchamel",             allergens: ["lait", "gluten"] },
  { name: "sauce velouté",              allergens: ["gluten"] },
  { name: "sauce vinaigrette",          allergens: [] },
  { name: "vinaigrette",                allergens: [] },
  { name: "sauce césar",                allergens: ["poissons", "oeufs", "lait"] },
  { name: "sauce gribiche",             allergens: ["oeufs", "moutarde"] },
  { name: "sauce tartare",              allergens: ["oeufs", "moutarde"] },
  { name: "sauce ravigote",             allergens: ["moutarde"] },
  { name: "sauce remoulade",            allergens: ["oeufs", "moutarde", "celeri"] },
  { name: "sauce bourguignonne",        allergens: ["so2"] },
  { name: "sauce au vin",               allergens: ["so2"] },
  { name: "sauce bigarrade",            allergens: [] },
  { name: "sauce vierge",               allergens: [] },
  { name: "pistou",                     allergens: [] },
  { name: "pesto",                      allergens: ["fruits_coq", "lait"] },
  { name: "pesto alla genovese",        allergens: ["fruits_coq", "lait"] },
  { name: "tapenade",                   allergens: [] },
  { name: "anchoïade",                  allergens: ["poissons"] },
  { name: "rouille",                    allergens: ["oeufs"] },
  { name: "tzatziki",                   allergens: ["lait"] },
  { name: "sauce tahini",               allergens: ["sesame"] },
  { name: "sauce raïta",                allergens: ["lait"] },
  { name: "sauce curry",                allergens: [] },
  { name: "sauce tikka masala",         allergens: ["lait"] },
  { name: "sauce bouillabaisse",        allergens: ["poissons", "crustaces"] },

  // ── PÂTISSERIE & VIENNOISERIE ────────────────────────────────────────────
  { name: "pâte brisée",                allergens: ["gluten", "lait"] },
  { name: "pâte feuilletée",            allergens: ["gluten", "lait"] },
  { name: "pâte sablée",                allergens: ["gluten", "lait", "oeufs"] },
  { name: "pâte à choux",               allergens: ["gluten", "lait", "oeufs"] },
  { name: "pâte à crêpes",              allergens: ["gluten", "lait", "oeufs"] },
  { name: "pâte à brioche",             allergens: ["gluten", "lait", "oeufs"] },
  { name: "pâte à pizza",               allergens: ["gluten"] },
  { name: "pâte à pain",                allergens: ["gluten"] },
  { name: "génoise",                    allergens: ["gluten", "oeufs"] },
  { name: "biscuit",                    allergens: ["gluten", "lait", "oeufs"] },
  { name: "biscuit de Savoie",          allergens: ["gluten", "oeufs"] },
  { name: "financier",                  allergens: ["gluten", "lait", "oeufs", "fruits_coq"] },
  { name: "madeleine",                  allergens: ["gluten", "lait", "oeufs"] },
  { name: "croissant",                  allergens: ["gluten", "lait", "oeufs"] },
  { name: "pain au chocolat",           allergens: ["gluten", "lait", "oeufs"] },
  { name: "brioche",                    allergens: ["gluten", "lait", "oeufs"] },
  { name: "tarte",                      allergens: ["gluten", "lait"] },
  { name: "quiche",                     allergens: ["gluten", "lait", "oeufs"] },
  { name: "éclair",                     allergens: ["gluten", "lait", "oeufs"] },
  { name: "choux",                      allergens: ["gluten", "lait", "oeufs"] },
  { name: "profiterole",                allergens: ["gluten", "lait", "oeufs"] },
  { name: "mille-feuille",              allergens: ["gluten", "lait", "oeufs"] },
  { name: "macaron",                    allergens: ["oeufs", "fruits_coq"] },
  { name: "canelé",                     allergens: ["gluten", "lait", "oeufs"] },
  { name: "kouign-amann",               allergens: ["gluten", "lait"] },
  { name: "far breton",                 allergens: ["gluten", "lait", "oeufs"] },
  { name: "clafoutis",                  allergens: ["gluten", "lait", "oeufs"] },
  { name: "fondant au chocolat",        allergens: ["gluten", "lait", "oeufs"] },
  { name: "brownie",                    allergens: ["gluten", "lait", "oeufs", "fruits_coq"] },
  { name: "crème caramel",              allergens: ["lait", "oeufs"] },
  { name: "île flottante",              allergens: ["lait", "oeufs"] },
  { name: "mousse au chocolat",         allergens: ["oeufs", "lait"] },
  { name: "tiramisu",                   allergens: ["oeufs", "lait", "gluten"] },
  { name: "panna cotta",                allergens: ["lait"] },
  { name: "crème brûlée",               allergens: ["lait", "oeufs"] },
  { name: "soufflé",                    allergens: ["lait", "oeufs", "gluten"] },
  { name: "galette",                    allergens: ["gluten"] },
  { name: "crêpe",                      allergens: ["gluten", "lait", "oeufs"] },
  { name: "gaufre",                     allergens: ["gluten", "lait", "oeufs"] },
];

export function normalize(str) {
  return str.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

export function getSuggestions(query) {
  if (!query || query.length < 2) return [];
  const nq = normalize(query);
  return INGREDIENTS_DB
    .filter((d) => normalize(d.name).includes(nq))
    .sort((a, b) => {
      const an = normalize(a.name);
      const bn = normalize(b.name);
      if (an.startsWith(nq) && !bn.startsWith(nq)) return -1;
      if (!an.startsWith(nq) && bn.startsWith(nq)) return 1;
      return an.length - bn.length;
    })
    .slice(0, 8);
}

export function detectAllergens(ingredients) {
  const found = new Set();
  ingredients.forEach((ing) => {
    const ni = normalize(ing);
    INGREDIENTS_DB.forEach((d) => {
      if (normalize(d.name) === ni || ni.includes(normalize(d.name))) {
        d.allergens.forEach((a) => found.add(a));
      }
    });
  });
  return found;
}